// <auto-generated />
using System;
using KomürcüPeyzaj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KomürcüPeyzaj.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602092826_AddUrun")]
    partial class AddUrun
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("KomürcüPeyzaj.Models.Abonelik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Abonelikler");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.BlogYazisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Etiketler")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KapakGorsel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KisaAciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OkunmaSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("YayinTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("YayindaMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogYazilari");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.EkipUyesi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Biyografi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EkipUyeleri");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.Hizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaslangicFiyati")
                        .HasColumnType("TEXT");

                    b.Property<string>("GorselUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ikon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KisaAciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Hizmetler");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.IletisimMesaji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GonderimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OkunduMu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IletisimMesajlari");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.Proje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HizmetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KapakGorsel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OncesiGorsel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OneIkartilsinMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SonrasiGorsel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TamamlanmaTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HizmetId");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.ProjeGorsel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GorselUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjeId");

                    b.ToTable("ProjeGorseller");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.Referans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjeAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Puan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("YayindaMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Referanslar");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.SSSMadde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cevap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SSSMaddeleri");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.SiteAyarlari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeneyimYili")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleMapsEmbed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HakkimizdaMetni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MutluMusteri")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slogan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TamamlananProje")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TikTok")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteAyarlari");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("TEXT");

                    b.Property<string>("GorselUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KisaAciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StokVarMi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.Proje", b =>
                {
                    b.HasOne("KomürcüPeyzaj.Models.Hizmet", "Hizmet")
                        .WithMany("Projeler")
                        .HasForeignKey("HizmetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hizmet");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.ProjeGorsel", b =>
                {
                    b.HasOne("KomürcüPeyzaj.Models.Proje", "Proje")
                        .WithMany("Gorseller")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proje");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.Hizmet", b =>
                {
                    b.Navigation("Projeler");
                });

            modelBuilder.Entity("KomürcüPeyzaj.Models.Proje", b =>
                {
                    b.Navigation("Gorseller");
                });
#pragma warning restore 612, 618
        }
    }
}
